apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
      - name: pre-install-task
        image: busybox:1.35
        command: ["sh", "-c", "echo 'Running pre-install task'; sleep 5"]
      restartPolicy: Never
  backoffLimit: 1
